<h1 style="text-align:center">Correction du TP sur les premiers pas avec SQL

## 1. Comment créer des tables ?

On reprend ici la base de données relationnelles vue en cours :
<table>
    <caption>Relation <em>livre</em> :</caption>
<thead>
<tr>
<th>id</th>
<th>titre</th>
<th>id_auteur</th>
<th>ann_publi</th>
<th>note</th>
</tr>
</thead>
<tbody><tr>
<td>1</td>
<td>1984</td>
<td>1</td>
<td>1949</td>
<td>10</td>
</tr>
<tr>
<td>2</td>
<td>Dune</td>
<td>2</td>
<td>1965</td>
<td>8</td>
</tr>
<tr>
<td>3</td>
<td>Fondation</td>
<td>3</td>
<td>1951</td>
<td>9</td>
</tr>
<tr>
<td>4</td>
<td>Fahrenheit 451</td>
<td>4</td>
<td>1953</td>
<td>7</td>
</tr>
<tr>
<td>5</td>
<td>Ubik</td>
<td>5</td>
<td>1969</td>
<td>9</td>
</tr>
<tr>
<td>6</td>
<td>Chroniques martiennes</td>
<td>4</td>
<td>1950</td>
<td>8</td>
</tr>
<tr>
<td>7</td>
<td>La nuit des temps</td>
<td>6</td>
<td>1968</td>
<td>7</td>
</tr>
<tr>
<td>8</td>
<td>Blade Runner</td>
<td>5</td>
<td>1968</td>
<td>8</td>
</tr>
<tr>
<td>9</td>
<td>Les Robots</td>
<td>3</td>
<td>1950</td>
<td>9</td>
</tr>
<tr>
<td>10</td>
<td>La planète des singes</td>
<td>7</td>
<td>1963</td>
<td>8</td>
</tr>
<tr>
<td>11</td>
<td>Ravage</td>
<td>6</td>
<td>1943</td>
<td>8</td>
</tr>
<tr>
<td>12</td>
<td>Le Maître du Haut Château</td>
<td>5</td>
<td>1962</td>
<td>8</td>
</tr>
<tr>
<td>13</td>
<td>La fin de l'éternité</td>
<td>3</td>
<td>1955</td>
<td>8</td>
</tr>
<tr>
<td>14</td>
<td>De la Terre à la Lune</td>
<td>8</td>
<td>1865</td>
<td>10</td>
</tr>
</tbody></table>


<br>

<table>
    <caption>Relation <em>auteur</em> :</caption>
<thead>
<tr>
<th>id</th>
<th>nom</th>
<th>prenom</th>
<th>ann_naiss</th>
<th>langue_ecrit</th>
</tr>
</thead>
<tbody><tr>
<td>1</td>
<td>Orwell</td>
<td>Georges</td>
<td>1903</td>
<td>anglais</td>
</tr>
<tr>
<td>2</td>
<td>Herbert</td>
<td>Frank</td>
<td>1920</td>
<td>anglais</td>
</tr>
<tr>
<td>3</td>
<td>Asimov</td>
<td>Isaac</td>
<td>1920</td>
<td>anglais</td>
</tr>
<tr>
<td>4</td>
<td>Bradbury</td>
<td>Ray</td>
<td>1920</td>
<td>anglais</td>
</tr>
<tr>
<td>5</td>
<td>K. Dick</td>
<td>Philip</td>
<td>1928</td>
<td>anglais</td>
</tr>
<tr>
<td>6</td>
<td>Barjavel</td>
<td>René</td>
<td>1911</td>
<td>français</td>
</tr>
<tr>
<td>7</td>
<td>Boulle</td>
<td>Pierre</td>
<td>1912</td>
<td>français</td>
</tr>
<tr>
<td>8</td>
<td>Verne</td>
<td>Jules</td>
<td>1828</td>
<td>français</td>
</tr>
</tbody></table>

Pour créer la 1ère table, on écrit ceci en langage SQL (pensez à exécuter les cellules mais qu'une seule fois) :

In [1]:
/* création de la table livre*/
DROP TABLE IF EXISTS livre;            -- au cas où une table livre existerait déjà
CREATE TABLE livre (                   -- DROP TABLE livre supprime la table livre (là on le fait seulement si elle existe)
    id INTEGER PRIMARY KEY NOT NULL,       -- on définit l'attribut id comme clef primaire
    titre TEXT NOT NULL,                   -- le NOT NULL signifie qu'on n'accepte pas d'absence de valeur pour tel attribut
    id_auteur INTEGER REFERENCES auteur (id) NOT NULL,  -- on définit l'attribut id_auteur comme clef étrangère
    ann_publi INTEGER,
    note INTEGER,
    CHECK (note>=0 AND note<=10)           -- pour spécifier que la note devra être comprise entre 0 et 10
    );

### Remarque.
*Le langage SQL ne tient pas du tout compte de la casse (autrement dit, pour lui minuscule=minuscule). Pour plus de lisibilité, on mettra les mots clés en majuscule et le reste en minuscule.*

<h3 style="color:blue">Exercice 1</h3>
Créer la table <em>auteur</em> en langage SQL puis exécuter la cellule (une seule fois) :

In [2]:
/* création de la table auteur*/
-- à vous d'écire le code en langage SQL en vous aidant de la création de la table livre faite plus haut --
DROP TABLE IF EXISTS auteur;
CREATE TABLE auteur (
    id INTEGER PRIMARY KEY NOT NULL,
    nom TEXT NOT NULL,
    prenom TEXT,
    ann_naiss INTEGER,
    langue_ecrit TEXT
    );

Autre possibilité : en indiquant à la fin la clé primaire

In [79]:
/* création de la table auteur : 2ème possibilité*/
DROP TABLE IF EXISTS auteur;
CREATE TABLE auteur (
    id INTEGER NOT NULL,
    nom TEXT NOT NULL,
    prenom TEXT,
    ann_naiss INTEGER,
    langue_ecrit TEXT,
    PRIMARY KEY (id)
    );

### Remarque.
En principe, on aurait dû créer la table *auteur* avant la table *livre* car un attribut de la table *livre* (id_auteur) fait référence à un attribut de la table *auteur* (id). Pour des raisons pédagogiques, j'ai fait le choix de créer la table la plus complexe avant, à savoir la table *livre*.

## 2. Comment insérer des enregistrements ?

In [3]:
/* remplissage de la table auteur */
INSERT INTO auteur
VALUES 
(1,'Orwell','Georges',1903,'anglais'),
(2,'Herbert','Frank',1920,'anglais'),
(3,'Asimov','Isaac',1920,'anglais'),
(4,'Bradbury','Ray',1920,'anglais'),
(5,'K. Dick','Philip',1928,'anglais'),
(6,'Barjavel','René',1911,'français'),
(7,'Boulle','Pierre',1912,'français'),
(8,'Verne','Jules',1828,'français');

In [4]:
/* remplissage de la table livre */
INSERT INTO livre
VALUES
(1,'1984',1,1949,10),
(2,'Dune',2,1965,8),
(3,'Fondation',3,1951,9),
(4,'Fahrenheit 451',4,1953,7),
(5,'Ubik',5,1969,9),
(6,'Chroniques martiennes',4,1950,8),
(7,'La nuit des temps',6,1968,7),
(8,'Blade Runner',5,1968,8),
(9,'Les Robots',3,1950,9),
(10,'La planète des singes',7,1963,8),
(11,'Ravage',6,1943,8),
(12,'Le Maître du Haut Château',5,1962,8),
(13,'La fin de l''éternité',3,1955,8),
(14,'De la Terre à la Lune',8,1865,10);

### L'intérêt d'une contrainte d'unicité

Exécutez la cellule suivante et constatez qu'elle produit une erreur. On ne peut pas en effet avoir de doublons pour une clef primaire !

In [5]:
INSERT INTO auteur
VALUES
(1, 'Daudet', 'Alphonse',1840,'français');

Error: UNIQUE constraint failed: auteur.id

Error:

Par contre, l'insertion suivante est valide (exécutez-là mais une seule fois) :

In [6]:
INSERT INTO auteur
VALUES
(9, 'Daudet', 'Alphonse',1840,'français');

### L'intérêt d'une contrainte métier

Exécutez la cellule suivante et constatez qu'elle produit également une erreur. En effet, quand on a défini la table, on a spécifié qu'une note devait toujours être comprise entre 0 et 10.

In [9]:
INSERT INTO livre
VALUES
(15, 'Les lettres de mon moulin',9,1869,11);

Error: CHECK constraint failed: note>=0 AND note<=10

Error:

Par contre ça fonctionne très bien quand on respecte les différentes conrtaintes. Exécutez la cellule suivante et constatez qu'il n'y a pas d'erreur.

In [10]:
INSERT INTO livre
VALUES
(15, 'Les lettres de mon moulin',9,1869,6);

Error: UNIQUE constraint failed: livre.id

Error:

## 3. Comment écrire des requêtes ?

### Pour visualiser une table entière : `SELECT * FROM <nom_table> `
    
    

Exécutez la cellule suivante et constatez qu'on visualise tous les attributs de la table livre.

In [11]:
SELECT * FROM livre;

id	titre	id_auteur	ann_publi	note
1	1984	1	1949	10
2	Dune	2	1965	8
3	Fondation	3	1951	9
4	Fahrenheit 451	4	1953	7
5	Ubik	5	1969	9
6	Chroniques martiennes	4	1950	8
7	La nuit des temps	6	1968	7
8	Blade Runner	5	1968	8
9	Les Robots	3	1950	9
10	La planète des singes	7	1963	8
11	Ravage	6	1943	8
12	Le Maître du Haut Château	5	1962	8
13	La fin de l'éternité	3	1955	8
14	De la Terre à la Lune	8	1865	10
15	Les lettres de mon moulin	9	1869	6

### La projection : `SELECT <nom_attribut>, <nom_attribut> FROM <nom_table>`

Pour sélectionner une ou plusieurs colonnes : 

<table>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background-color:orange"></td>
    </tr>
</table>

Exécutez la cellule suivante et constatez qu'on visualise seulement les attributs titre, note et ann_publ (dans cet ordre) de la table livre

In [12]:
SELECT titre,note,ann_publi FROM livre;

titre	note	ann_publi
1984	10	1949
Dune	8	1965
Fondation	9	1951
Fahrenheit 451	7	1953
Ubik	9	1969
Chroniques martiennes	8	1950
La nuit des temps	7	1968
Blade Runner	8	1968
Les Robots	9	1950
La planète des singes	8	1963
Ravage	8	1943
Le Maître du Haut Château	8	1962
La fin de l'éternité	8	1955
De la Terre à la Lune	10	1865
Les lettres de mon moulin	6	1869

### avec le mot clé AS, il est possible de renommer des colonnes ou même de créer de nouvelles

In [13]:
SELECT titre,ann_publi AS année_de_publication,note AS note_sur_10 FROM livre;

titre	année_de_publication	note_sur_10
1984	1949	10
Dune	1965	8
Fondation	1951	9
Fahrenheit 451	1953	7
Ubik	1969	9
Chroniques martiennes	1950	8
La nuit des temps	1968	7
Blade Runner	1968	8
Les Robots	1950	9
La planète des singes	1963	8
Ravage	1943	8
Le Maître du Haut Château	1962	8
La fin de l'éternité	1955	8
De la Terre à la Lune	1865	10
Les lettres de mon moulin	1869	6

In [14]:
SELECT titre,ann_publi AS année_de_publication,note*2 AS note_sur_20 FROM livre;

titre	année_de_publication	note_sur_20
1984	1949	20
Dune	1965	16
Fondation	1951	18
Fahrenheit 451	1953	14
Ubik	1969	18
Chroniques martiennes	1950	16
La nuit des temps	1968	14
Blade Runner	1968	16
Les Robots	1950	18
La planète des singes	1963	16
Ravage	1943	16
Le Maître du Haut Château	1962	16
La fin de l'éternité	1955	16
De la Terre à la Lune	1865	20
Les lettres de mon moulin	1869	12

### Restriction : `SELECT * FROM <nom_table> WHERE <condition>`
    
Pour sélectionner toutes les lignes vérifiant la condition donnée

    
<table>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
    </tr>
    <tr>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
    </tr>
    <tr>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
    </tr>
    
</table>
    
### restriction avec projection : `SELECT * FROM <nom_table> WHERE <condition>`

On va combiner les deux pour obtenir seulement les cases rouges
<table>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid"></td>
    </tr>
    <tr>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:red"></td>
        <td style="border:1px solid; background:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid"></td>
    </tr>
    <tr>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid; background:red"></td>
        <td style="border:1px solid; background:orange"></td>
    </tr>
    <tr>
        <td style="border:1px solid"></td>
        <td style="border:1px solid"></td>
        <td style="border:1px solid; background:orange"></td>
        <td style="border:1px solid"></td>
    </tr>
    
</table>

les conditions courantes : 
    
    <nom_attribut> [=, >, <, <=, >=] <valeur>
    <nom_attribut> LIKE <chaîne de caractères avec des caractères génériques comme % ou _>

Le caractère `_` représente n'importe quel caractère et `%` n'importe quelle chaîne de caractères. On peut les insérer n'importe où dans la chaîne de caractères de comparaison.

Par ex : 
``` SQL 
SELECT * FROM auteur WHERE nom LIKE '%a%'```
sélectionne toutes les lignes dont le *nom* est une chaîne de caractères contenant un *a* (ou un *A* : le langage SQL ne tient pas compte de la casse).

Exécutez les 3 cellules suivantes et vérifiez à chaque fois qu'on visualise les lignes vérifiant la condition donnée

In [15]:
SELECT titre,note FROM livre WHERE note>=9;

titre	note
1984	10
Fondation	9
Ubik	9
Les Robots	9
De la Terre à la Lune	10

In [16]:
SELECT nom,prenom,ann_naiss AS année_de_naissance FROM auteur WHERE nom LIKE '%a%';

nom	prenom	année_de_naissance
Asimov	Isaac	1920
Bradbury	Ray	1920
Barjavel	René	1911
Daudet	Alphonse	1840

In [17]:
SELECT nom,prenom,ann_naiss AS année_de_naissance FROM auteur WHERE nom LIKE 'b%';

nom	prenom	année_de_naissance
Bradbury	Ray	1920
Barjavel	René	1911
Boulle	Pierre	1912

In [18]:
SELECT titre,ann_publi AS année_de_publication FROM livre WHERE ann_publi LIKE '19_3';

titre	année_de_publication
Fahrenheit 451	1953
La planète des singes	1963
Ravage	1943

Voici deux instructions (à exécuter) permettant d'afficher tous les titres et leurs années de publication dont l'année de publication est comprise (au sens large) entre 1962 et 1969.

In [19]:
SELECT titre,ann_publi AS année_de_publication FROM livre WHERE ann_publi>=1962 AND ann_publi<=1969;

titre	année_de_publication
Dune	1965
Ubik	1969
La nuit des temps	1968
Blade Runner	1968
La planète des singes	1963
Le Maître du Haut Château	1962

In [20]:
SELECT titre,ann_publi AS année_de_publication FROM livre WHERE ann_publi BETWEEN 1962 AND 1969;

titre	année_de_publication
Dune	1965
Ubik	1969
La nuit des temps	1968
Blade Runner	1968
La planète des singes	1963
Le Maître du Haut Château	1962

On peut aussi vouloir afficher tous les films et leurs notes dont l'année de publication est compris entre 1962 et 1969.

In [21]:
SELECT titre,note FROM livre WHERE ann_publi>=1962 AND ann_publi<=1969;

titre	note
Dune	8
Ubik	9
La nuit des temps	7
Blade Runner	8
La planète des singes	8
Le Maître du Haut Château	8

<h3 style="color:blue">Exercice 2</h3>
<h4>Question 1</h4>
Afficher tous les titres commençant par la lettre L

In [98]:
SELECT titre FROM livre WHERE titre LIKE 'L%';

titre
La nuit des temps
Les Robots
La planète des singes
Le Maître du Haut Château
La fin de l'éternité
Les lettres de mon moulin

#### Question 2
Afficher les noms, prénoms et année de naissance de tous les auteurs dont l'année de naissance est strictement
inférieur à 1900 ou strictement supérieur à 1920.

In [99]:
SELECT nom,prenom,ann_naiss AS année_de_naissance FROM auteur WHERE ann_naiss<1900 OR ann_naiss>1920;

nom	prenom	année_de_naissance
K. Dick	Philip	1928
Verne	Jules	1828
Daudet	Alphonse	1840

### Le tri avec la clause ORDER BY en fin de requête
Pour afficher tous les films par ordre alphabétique avec leurs années de publication :

In [100]:
SELECT titre,ann_publi AS année_de_publication FROM livre ORDER BY titre ASC;

titre	année_de_publication
1984	1949
Blade Runner	1968
Chroniques martiennes	1950
De la Terre à la Lune	1865
Dune	1965
Fahrenheit 451	1953
Fondation	1951
La fin de l'éternité	1955
La nuit des temps	1968
La planète des singes	1963
Le Maître du Haut Château	1962
Les Robots	1950
Les lettres de mon moulin	1869
Ravage	1943
Ubik	1969

Comme par défaut, le tri est croissant, on peut omettre `ASC` (pour ascendant) :

In [101]:
SELECT titre,ann_publi AS année_de_publication FROM livre ORDER BY titre;

titre	année_de_publication
1984	1949
Blade Runner	1968
Chroniques martiennes	1950
De la Terre à la Lune	1865
Dune	1965
Fahrenheit 451	1953
Fondation	1951
La fin de l'éternité	1955
La nuit des temps	1968
La planète des singes	1963
Le Maître du Haut Château	1962
Les Robots	1950
Les lettres de mon moulin	1869
Ravage	1943
Ubik	1969

Pour trier par ordre décroissant, on précise le mot clé `DESC` (pour descendant) :

In [102]:
SELECT titre,ann_publi AS année_de_publication FROM livre ORDER BY titre DESC;

titre	année_de_publication
Ubik	1969
Ravage	1943
Les lettres de mon moulin	1869
Les Robots	1950
Le Maître du Haut Château	1962
La planète des singes	1963
La nuit des temps	1968
La fin de l'éternité	1955
Fondation	1951
Fahrenheit 451	1953
Dune	1965
De la Terre à la Lune	1865
Chroniques martiennes	1950
Blade Runner	1968
1984	1949

### Suppression des doublons avec le mot clé `DISTINCT`
Pour afficher les différentes langues des auteurs sans les doublons :

In [103]:
SELECT DISTINCT langue_ecrit FROM auteur;

langue_ecrit
anglais
français

<h3 style="color:blue">Exercice 3</h3>
<h4>Question 1</h4>
Afficher tous les titres par ordre croissant d'année de publication

In [104]:
SELECT titre,ann_publi AS année_de_publication FROM livre ORDER BY ann_publi;

titre	année_de_publication
De la Terre à la Lune	1865
Les lettres de mon moulin	1869
Ravage	1943
1984	1949
Chroniques martiennes	1950
Les Robots	1950
Fondation	1951
Fahrenheit 451	1953
La fin de l'éternité	1955
Le Maître du Haut Château	1962
La planète des singes	1963
Dune	1965
La nuit des temps	1968
Blade Runner	1968
Ubik	1969

#### Question 2
Afficher toutes les années de naissance des auteurs sans les doublons dans l'ordre décroissant

In [105]:
SELECT DISTINCT ann_naiss AS année_de_naissance FROM auteur ORDER BY ann_naiss DESC;

année_de_naissance
1928
1920
1912
1911
1903
1840
1828

## Fonctions d'agrégation

Les fonctions d'agrégation permettent d'appliquer une fonction à l'ensemble des valeurs d'une colonne (ou de plusieurs colonnes) et de renvoyer le résultat comme une table à 1 seule ligne et 1 seule colonne.

Voici quelques fonctions d'agrégations :
+ `COUNT` permettant de compter le nombre d'entrées non vide
+ `AVG` (pour <em>average</em> en anglais qui signifie moyenne) permettant de calculer la moyenne d'une colonne
+ `SUM` permettant de calculer la somme d'une colonne
+ `MIN` et `MAX` permettant de trouver respectivement le minimum et le maximum d'une colonne 

Dans une telle requête, il faut bien décomposer les choses pour construire la requête : d'abord, le résultat qui va faire un certain nombre de lignes, puis la fonction d'agrégation qui est appliquée sur ce résultat. 

Exécutez la cellule suivante et vérifiez qu'elle affiche bien le nombre de lignes de la table livre

In [106]:
SELECT COUNT (*) FROM livre;

COUNT (*)
15

On préfère renommer le titre avec le mot clé `AS`

In [107]:
SELECT COUNT (*) AS Total FROM livre;

Total
15

On peut vouloir obtenir la note moyenne des livres :

In [108]:
SELECT AVG (note) AS note_moyenne FROM livre;

note_moyenne
8.2

ou bien obtenir le nombre d'auteurs anglais dans la table auteur

In [109]:
SELECT COUNT (*) AS nombre_d_auteurs_anglais FROM auteur WHERE langue_ecrit='anglais';

nombre_d_auteurs_anglais
5

ou bien connaître le nombre de langues distinctes de la table auteur

In [110]:
SELECT COUNT (DISTINCT langue_ecrit) AS nombre_de_langues FROM auteur;

nombre_de_langues
2

<h3 style="color:blue">Exercice 4</h3>
<h4>Question 1</h4>
Afficher le nombre de livres dont l'année de publication est comprise (au sens large) entre 1940 et 1960

In [111]:
SELECT COUNT (*) AS nombre_de_livres_entre_1940_et_1960 FROM livre WHERE ann_publi>=1940 AND ann_publi<=1960;

nombre_de_livres_entre_1940_et_1960
7

#### Question 2
Afficher l'année de publication la plus récente dont les titres commencent par la lettre L

In [112]:
SELECT MAX (ann_publi) AS année_de_publication_la_plus_récente FROM livre WHERE titre LIKE 'L%';

année_de_publication_la_plus_récente
1968

## Jointures

Il arrive que l'information sur une entité soit dispersée dans deux tables. On doit alors utiliser une jointure. 

Par ex. quels sont les titres des livres écrits par K. Dick ?

Quand l'information est dispersée dans deux tables T1 et T2, la jointure consiste à constuire d'abord une sorte de grosse table où chaque ligne est composée d'une ligne de T1 et d'une ligne de T2 (on appelle cette étape le produit cartésien de T1 avec T2). Cette grosse table contient le nombre de lignes dans T1 multiplié par le nombre de lignes dans T2.

In [113]:
SELECT * FROM livre JOIN auteur;

id	titre	id_auteur	ann_publi	note	id	nom	prenom	ann_naiss	langue_ecrit
1	1984	1	1949	10	1	Orwell	Georges	1903	anglais
1	1984	1	1949	10	2	Herbert	Frank	1920	anglais
1	1984	1	1949	10	3	Asimov	Isaac	1920	anglais
1	1984	1	1949	10	4	Bradbury	Ray	1920	anglais
1	1984	1	1949	10	5	K. Dick	Philip	1928	anglais
1	1984	1	1949	10	6	Barjavel	René	1911	français
1	1984	1	1949	10	7	Boulle	Pierre	1912	français
1	1984	1	1949	10	8	Verne	Jules	1828	français
1	1984	1	1949	10	9	Daudet	Alphonse	1840	français
2	Dune	2	1965	8	1	Orwell	Georges	1903	anglais
2	Dune	2	1965	8	2	Herbert	Frank	1920	anglais
2	Dune	2	1965	8	3	Asimov	Isaac	1920	anglais
2	Dune	2	1965	8	4	Bradbury	Ray	1920	anglais
2	Dune	2	1965	8	5	K. Dick	Philip	1928	anglais
2	Dune	2	1965	8	6	Barjavel	René	1911	français
2	Dune	2	1965	8	7	Boulle	Pierre	1912	français
2	Dune	2	1965	8	8	Verne	Jules	1828	français
2	Dune	2	1965	8	9	Daudet	Alphonse	1840	français
3	Fondation	3	1951	9	1	Orwell	Georges	1903	anglais
3	Fondation	3	1951	9	2	Herbert	Frank	1920	anglais
3	Fondation	3	1951	9	3	Asimov	Isaac	1920	anglais
3	Fondation	3	1951	9	4	Bradbury	Ray	1920	anglais
3	Fondation	3	1951	9	5	K. Dick	Philip	1928	anglais
3	Fondation	3	1951	9	6	Barjavel	René	1911	français
3	Fondation	3	1951	9	7	Boulle	Pierre	1912	français
3	Fondation	3	1951	9	8	Verne	Jules	1828	français
3	Fondation	3	1951	9	9	Daudet	Alphonse	1840	français
4	Fahrenheit 451	4	1953	7	1	Orwell	Georges	1903	anglais
4	Fahrenheit 451	4	1953	7	2	Herbert	Frank	1920	anglais
4	Fahrenheit 451	4	1953	7	3	Asimov	Isaac	1920	anglais
4	Fahrenheit 451	4	1953	7	4	Bradbury	Ray	1920	anglais
4	Fahrenheit 451	4	1953	7	5	K. Dick	Philip	1928	anglais
4	Fahrenheit 451	4	1953	7	6	Barjavel	René	1911	français
4	Fahrenheit 451	4	1953	7	7	Boulle	Pierre	1912	français
4	Fahrenheit 451	4	1953	7	8	Verne	Jules	1828	français
4	Fahrenheit 451	4	1953	7	9	Daudet	Alphonse	1840	français
5	Ubik	5	1969	9	1	Orwell	Georges	1903	anglais
5	Ubik	5	1969	9	2	Herbert	Frank	1920	anglais
5	Ubik	5	1969	9	3	Asimov	Isaac	1920	anglais
5	Ubik	5	1969	9	4	Bradbury	Ray	1920	anglais
5	Ubik	5	1969	9	5	K. Dick	Philip	1928	anglais
5	Ubik	5	1969	9	6	Barjavel	René	1911	français
5	Ubik	5	1969	9	7	Boulle	Pierre	1912	français
5	Ubik	5	1969	9	8	Verne	Jules	1828	français
5	Ubik	5	1969	9	9	Daudet	Alphonse	1840	français
6	Chroniques martiennes	4	1950	8	1	Orwell	Georges	1903	anglais
6	Chroniques martiennes	4	1950	8	2	Herbert	Frank	1920	anglais
6	Chroniques martiennes	4	1950	8	3	Asimov	Isaac	1920	anglais
6	Chroniques martiennes	4	1950	8	4	Bradbury	Ray	1920	anglais
6	Chroniques martiennes	4	1950	8	5	K. Dick	Philip	1928	anglais
6	Chroniques martiennes	4	1950	8	6	Barjavel	René	1911	français
6	Chroniques martiennes	4	1950	8	7	Boulle	Pierre	1912	français
6	Chroniques martiennes	4	1950	8	8	Verne	Jules	1828	français
6	Chroniques martiennes	4	1950	8	9	Daudet	Alphonse	1840	français
7	La nuit des temps	6	1968	7	1	Orwell	Georges	1903	anglais
7	La nuit des temps	6	1968	7	2	Herbert	Frank	1920	anglais
7	La nuit des temps	6	1968	7	3	Asimov	Isaac	1920	anglais
7	La nuit des temps	6	1968	7	4	Bradbury	Ray	1920	anglais
7	La nuit des temps	6	1968	7	5	K. Dick	Philip	1928	anglais
7	La nuit des temps	6	1968	7	6	Barjavel	René	1911	français
7	La nuit des temps	6	1968	7	7	Boulle	Pierre	1912	français
7	La nuit des temps	6	1968	7	8	Verne	Jules	1828	français
7	La nuit des temps	6	1968	7	9	Daudet	Alphonse	1840	français
8	Blade Runner	5	1968	8	1	Orwell	Georges	1903	anglais
8	Blade Runner	5	1968	8	2	Herbert	Frank	1920	anglais
8	Blade Runner	5	1968	8	3	Asimov	Isaac	1920	anglais
8	Blade Runner	5	1968	8	4	Bradbury	Ray	1920	anglais
8	Blade Runner	5	1968	8	5	K. Dick	Philip	1928	anglais
8	Blade Runner	5	1968	8	6	Barjavel	René	1911	français
8	Blade Runner	5	1968	8	7	Boulle	Pierre	1912	français
8	Blade Runner	5	1968	8	8	Verne	Jules	1828	français
8	Blade Runner	5	1968	8	9	Daudet	Alphonse	1840	français
9	Les Robots	3	1950	9	1	Orwell	Georges	1903	anglais
9	Les Robots	3	1950	9	2	Herbert	Frank	1920	anglais
9	Les Robots	3	1950	9	3	Asimov	Isaac	1920	anglais
9	Les Robots	3	1950	9	4	Bradbury	Ray	1920	anglais
9	Les Robots	3	1950	9	5	K. Dick	Philip	1928	anglais
9	Les Robots	3	1950	9	6	Barjavel	René	1911	français
9	Les Robots	3	1950	9	7	Boulle	Pierre	1912	français
9	Les Robots	3	1950	9	8	Verne	Jules	1828	français
9	Les Robots	3	1950	9	9	Daudet	Alphonse	1840	français
10	La planète des singes	7	1963	8	1	Orwell	Georges	1903	anglais
10	La planète des singes	7	1963	8	2	Herbert	Frank	1920	anglais
10	La planète des singes	7	1963	8	3	Asimov	Isaac	1920	anglais
10	La planète des singes	7	1963	8	4	Bradbury	Ray	1920	anglais
10	La planète des singes	7	1963	8	5	K. Dick	Philip	1928	anglais
10	La planète des singes	7	1963	8	6	Barjavel	René	1911	français
10	La planète des singes	7	1963	8	7	Boulle	Pierre	1912	français
10	La planète des singes	7	1963	8	8	Verne	Jules	1828	français
10	La planète des singes	7	1963	8	9	Daudet	Alphonse	1840	français
11	Ravage	6	1943	8	1	Orwell	Georges	1903	anglais
11	Ravage	6	1943	8	2	Herbert	Frank	1920	anglais
11	Ravage	6	1943	8	3	Asimov	Isaac	1920	anglais
11	Ravage	6	1943	8	4	Bradbury	Ray	1920	anglais
11	Ravage	6	1943	8	5	K. Dick	Philip	1928	anglais
11	Ravage	6	1943	8	6	Barjavel	René	1911	français
11	Ravage	6	1943	8	7	Boulle	Pierre	1912	français
11	Ravage	6	1943	8	8	Verne	Jules	1828	français
11	Ravage	6	1943	8	9	Daudet	Alphonse	1840	français
12	Le Maître du Haut Château	5	1962	8	1	Orwell	Georges	1903	anglais
12	Le Maître du Haut Château	5	1962	8	2	Herbert	Frank	1920	anglais
12	Le Maître du Haut Château	5	1962	8	3	Asimov	Isaac	1920	anglais
12	Le Maître du Haut Château	5	1962	8	4	Bradbury	Ray	1920	anglais
12	Le Maître du Haut Château	5	1962	8	5	K. Dick	Philip	1928	anglais
12	Le Maître du Haut Château	5	1962	8	6	Barjavel	René	1911	français
12	Le Maître du Haut Château	5	1962	8	7	Boulle	Pierre	1912	français
12	Le Maître du Haut Château	5	1962	8	8	Verne	Jules	1828	français
12	Le Maître du Haut Château	5	1962	8	9	Daudet	Alphonse	1840	français
13	La fin de l'éternité	3	1955	8	1	Orwell	Georges	1903	anglais
13	La fin de l'éternité	3	1955	8	2	Herbert	Frank	1920	anglais
13	La fin de l'éternité	3	1955	8	3	Asimov	Isaac	1920	anglais
13	La fin de l'éternité	3	1955	8	4	Bradbury	Ray	1920	anglais
13	La fin de l'éternité	3	1955	8	5	K. Dick	Philip	1928	anglais
13	La fin de l'éternité	3	1955	8	6	Barjavel	René	1911	français
13	La fin de l'éternité	3	1955	8	7	Boulle	Pierre	1912	français
13	La fin de l'éternité	3	1955	8	8	Verne	Jules	1828	français
13	La fin de l'éternité	3	1955	8	9	Daudet	Alphonse	1840	français
14	De la Terre à la Lune	8	1865	10	1	Orwell	Georges	1903	anglais
14	De la Terre à la Lune	8	1865	10	2	Herbert	Frank	1920	anglais
14	De la Terre à la Lune	8	1865	10	3	Asimov	Isaac	1920	anglais
14	De la Terre à la Lune	8	1865	10	4	Bradbury	Ray	1920	anglais
14	De la Terre à la Lune	8	1865	10	5	K. Dick	Philip	1928	anglais
14	De la Terre à la Lune	8	1865	10	6	Barjavel	René	1911	français
14	De la Terre à la Lune	8	1865	10	7	Boulle	Pierre	1912	français
14	De la Terre à la Lune	8	1865	10	8	Verne	Jules	1828	français
14	De la Terre à la Lune	8	1865	10	9	Daudet	Alphonse	1840	français
15	Les lettres de mon moulin	9	1869	6	1	Orwell	Georges	1903	anglais
15	Les lettres de mon moulin	9	1869	6	2	Herbert	Frank	1920	anglais
15	Les lettres de mon moulin	9	1869	6	3	Asimov	Isaac	1920	anglais
15	Les lettres de mon moulin	9	1869	6	4	Bradbury	Ray	1920	anglais
15	Les lettres de mon moulin	9	1869	6	5	K. Dick	Philip	1928	anglais
15	Les lettres de mon moulin	9	1869	6	6	Barjavel	René	1911	français
15	Les lettres de mon moulin	9	1869	6	7	Boulle	Pierre	1912	français
15	Les lettres de mon moulin	9	1869	6	8	Verne	Jules	1828	français
15	Les lettres de mon moulin	9	1869	6	9	Daudet	Alphonse	1840	français

Le produit cartésien contient encore beaucoup trop d'informations et une telle jointure n'a pas grand intérêt. 

En face de chaque ligne d'un livre, on veut seulement l'auteur correspondant (et non pas comme précédemment tous les auteurs). 

En effet, les colonnes *id_auteur* de la table *livre* et *id* de la table *auteur* ont les mêmes valeurs. On peut alors faire une jointure sur les valeurs des ces colonnes similaires, qui vont servir de point de branchement.

In [114]:
SELECT * FROM livre JOIN auteur ON livre.id_auteur=auteur.id; -- on précise sur quoi on fait la jointure --

id	titre	id_auteur	ann_publi	note	id	nom	prenom	ann_naiss	langue_ecrit
1	1984	1	1949	10	1	Orwell	Georges	1903	anglais
2	Dune	2	1965	8	2	Herbert	Frank	1920	anglais
3	Fondation	3	1951	9	3	Asimov	Isaac	1920	anglais
4	Fahrenheit 451	4	1953	7	4	Bradbury	Ray	1920	anglais
5	Ubik	5	1969	9	5	K. Dick	Philip	1928	anglais
6	Chroniques martiennes	4	1950	8	4	Bradbury	Ray	1920	anglais
7	La nuit des temps	6	1968	7	6	Barjavel	René	1911	français
8	Blade Runner	5	1968	8	5	K. Dick	Philip	1928	anglais
9	Les Robots	3	1950	9	3	Asimov	Isaac	1920	anglais
10	La planète des singes	7	1963	8	7	Boulle	Pierre	1912	français
11	Ravage	6	1943	8	6	Barjavel	René	1911	français
12	Le Maître du Haut Château	5	1962	8	5	K. Dick	Philip	1928	anglais
13	La fin de l'éternité	3	1955	8	3	Asimov	Isaac	1920	anglais
14	De la Terre à la Lune	8	1865	10	8	Verne	Jules	1828	français
15	Les lettres de mon moulin	9	1869	6	9	Daudet	Alphonse	1840	français

C'est déjà beaucoup plus satisfaisant. Mais on peut vouloir ne pas afficher les colonnes avec les identifiants

In [115]:
SELECT livre.titre,livre.ann_publi,livre.note,auteur.nom,auteur.prenom,auteur.ann_naiss,auteur.langue_ecrit
FROM livre
JOIN auteur ON livre.id_auteur=auteur.id;

titre	ann_publi	note	nom	prenom	ann_naiss	langue_ecrit
1984	1949	10	Orwell	Georges	1903	anglais
Dune	1965	8	Herbert	Frank	1920	anglais
Fondation	1951	9	Asimov	Isaac	1920	anglais
Fahrenheit 451	1953	7	Bradbury	Ray	1920	anglais
Ubik	1969	9	K. Dick	Philip	1928	anglais
Chroniques martiennes	1950	8	Bradbury	Ray	1920	anglais
La nuit des temps	1968	7	Barjavel	René	1911	français
Blade Runner	1968	8	K. Dick	Philip	1928	anglais
Les Robots	1950	9	Asimov	Isaac	1920	anglais
La planète des singes	1963	8	Boulle	Pierre	1912	français
Ravage	1943	8	Barjavel	René	1911	français
Le Maître du Haut Château	1962	8	K. Dick	Philip	1928	anglais
La fin de l'éternité	1955	8	Asimov	Isaac	1920	anglais
De la Terre à la Lune	1865	10	Verne	Jules	1828	français
Les lettres de mon moulin	1869	6	Daudet	Alphonse	1840	français

On peut aussi mettre des alias avec le mot clé `AS` pour racourcir l'instruction

In [116]:
SELECT l.titre,l.ann_publi,l.note,a.nom,a.prenom,a.ann_naiss,a.langue_ecrit
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id;

titre	ann_publi	note	nom	prenom	ann_naiss	langue_ecrit
1984	1949	10	Orwell	Georges	1903	anglais
Dune	1965	8	Herbert	Frank	1920	anglais
Fondation	1951	9	Asimov	Isaac	1920	anglais
Fahrenheit 451	1953	7	Bradbury	Ray	1920	anglais
Ubik	1969	9	K. Dick	Philip	1928	anglais
Chroniques martiennes	1950	8	Bradbury	Ray	1920	anglais
La nuit des temps	1968	7	Barjavel	René	1911	français
Blade Runner	1968	8	K. Dick	Philip	1928	anglais
Les Robots	1950	9	Asimov	Isaac	1920	anglais
La planète des singes	1963	8	Boulle	Pierre	1912	français
Ravage	1943	8	Barjavel	René	1911	français
Le Maître du Haut Château	1962	8	K. Dick	Philip	1928	anglais
La fin de l'éternité	1955	8	Asimov	Isaac	1920	anglais
De la Terre à la Lune	1865	10	Verne	Jules	1828	français
Les lettres de mon moulin	1869	6	Daudet	Alphonse	1840	français

On peut vouloir afficher tous les livres écrits par K.Dick

In [117]:
SELECT l.titre,l.ann_publi,l.note
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id
WHERE a.nom='K. Dick';

titre	ann_publi	note
Ubik	1969	9
Blade Runner	1968	8
Le Maître du Haut Château	1962	8

**Remarque.** Il est possible de faire des jointures sur plus de 2 tables, il suffit de rajouter des `JOIN <table> ON <condition de jointure>`.

On peut vouloir calculer la moyenne des notes des livres de K. Dick

In [118]:
SELECT AVG (l.note) AS note_moyenne
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id
WHERE a.nom='K. Dick';

note_moyenne
8.333333333333334

<h3 style="color:blue">Exercice 5</h3>
<h4>Question 1</h4>
Afficher tous les titres des livres écrits en français

In [119]:
SELECT l.titre
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id
WHERE a.langue_ecrit='français';

titre
La nuit des temps
La planète des singes
Ravage
De la Terre à la Lune
Les lettres de mon moulin

#### Question 2
Afficher le nombre de livres écrits en français

In [120]:
SELECT COUNT(*) AS nombre_de_livres_écrits_en_français
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id
WHERE a.langue_ecrit='français';

nombre_de_livres_écrits_en_français
5

#### Question 3
Afficher les titres des livres, les noms et prénoms des auteurs ainsi que l'âge qu'ils avaient lors de la publication (dans l'ordre décroissant de l'âge)

In [121]:
SELECT l.titre,a.nom,a.prenom,l.ann_publi-a.ann_naiss AS âge_de_publication
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id
ORDER BY âge_de_publication DESC;

titre	nom	prenom	âge_de_publication
La nuit des temps	Barjavel	René	57
La planète des singes	Boulle	Pierre	51
1984	Orwell	Georges	46
Dune	Herbert	Frank	45
Ubik	K. Dick	Philip	41
Blade Runner	K. Dick	Philip	40
De la Terre à la Lune	Verne	Jules	37
La fin de l'éternité	Asimov	Isaac	35
Le Maître du Haut Château	K. Dick	Philip	34
Fahrenheit 451	Bradbury	Ray	33
Ravage	Barjavel	René	32
Fondation	Asimov	Isaac	31
Chroniques martiennes	Bradbury	Ray	30
Les Robots	Asimov	Isaac	30
Les lettres de mon moulin	Daudet	Alphonse	29

#### Question 4
Afficher l'âge moyen publication

In [122]:
SELECT AVG(l.ann_publi-a.ann_naiss) AS âge_moyen_de_publication
FROM livre AS l
JOIN auteur AS a ON l.id_auteur=a.id;

âge_moyen_de_publication
38.06666666666667

## 4. Comment modifier des données ?

Les données stockées dans une SGBD ne sont *a priori* pas figées et peuvent être modifiées au cours du temps. Nous allons montrer deux types de modifications pouvant être faites sur les tables :
- la suppression d'un ensemble de lignes
- la mise à jour de certains attributs d'un ensemble de lignes

### La suppression des lignes avec `DELETE FROM <table> WHERE <condition>`
Permet de supprimer toutes les lignes de la table vérifiant la condition donnée.

In [123]:
DELETE FROM livre WHERE ann_publi>1950;

Vérifions que l'instruction précédente a bien supprimé de la table livre toutes les lignes dont l'année de publication est strictement supérieure à 1950 :

In [124]:
SELECT * FROM livre;

id	titre	id_auteur	ann_publi	note
1	1984	1	1949	10
6	Chroniques martiennes	4	1950	8
9	Les Robots	3	1950	9
11	Ravage	6	1943	8
14	De la Terre à la Lune	8	1865	10
15	Les lettres de mon moulin	9	1869	6

### Attention à ne pas confondre les instructions `DELETE FROM <table>` et `DROP TABLE <table>`
- La 1ère supprime toutes les lignes de la table mais la table existe et on peut donc insérer des éléments,
- La 2nde supprime totalement la table.

### La mise à jour avec `UPDATE <table> SET <attribut>=<nouvelle_valeur> WHERE <condition>`
Sélectionne toutes les lignes de la table vérifiant la condition donnée et, pour chacune de ces lignes, remplace la valeur courante de l'attribut donné par la nouvelle valeur.

In [125]:
UPDATE auteur SET langue_ecrit='english' WHERE langue_ecrit='anglais';

Vérifiez que la table *auteur* a été correctement mise à jour en exécutant la cellule suivante

In [126]:
SELECT * FROM auteur;

id	nom	prenom	ann_naiss	langue_ecrit
1	Orwell	Georges	1903	english
2	Herbert	Frank	1920	english
3	Asimov	Isaac	1920	english
4	Bradbury	Ray	1920	english
5	K. Dick	Philip	1928	english
6	Barjavel	René	1911	français
7	Boulle	Pierre	1912	français
8	Verne	Jules	1828	français
9	Daudet	Alphonse	1840	français

<h3 style="color:blue">Exercice 6</h3>
<h4>Question 1</h4>
Supprimer de la table *auteur* tous ceux nés au XIXe siècle (on rappelle à cette occasion que le XIXe siècle commence le 1er janvier 1801 et finit le 31 décembre 1900).

<div class="alert alert-warning" style="border-left:15px solid #8a6d3b;"> <h3>Attention</h3>
Comme id_auteur de la table livre référence id de la table auteur, il faut d'abord supprimer les livres dont l'id_auteur sont concernés, donc on commence par chercher avec un JOIN les id_auteur dont les auteurs sont nés au XIXe siècle, ensuite on va supprimer les livres correspondant puis enfin supprimer les auteurs correspondant !
</div>

In [135]:
SELECT id_auteur FROM livre JOIN auteur ON livre.id_auteur=auteur.id WHERE auteur.ann_naiss<=1900 AND auteur.ann_naiss>1800;

In [136]:
DELETE FROM livre WHERE (id_auteur=8 OR id_auteur=9);

In [137]:
DELETE FROM auteur WHERE ann_naiss<=1900 AND ann_naiss>1800;

Vérifiez que la table *auteur* a été correctement mise à jour en exécutant la cellule suivante

In [138]:
SELECT * FROM auteur;

id	nom	prenom	ann_naiss	langue_ecrit
1	Orwell	Georges	1903	english
2	Herbert	Frank	1920	english
3	Asimov	Isaac	1920	english
4	Bradbury	Ray	1920	english
5	K. Dick	Philip	1928	english
6	Barjavel	René	1911	français
7	Boulle	Pierre	1912	français

#### Question 2
Les éditeurs se sont aperçus qu'ils ont noté trop large. Ils décident d'enlever 3 pts à chaque note. Faites cette modification.

In [139]:
UPDATE livre SET note=note-3;

Vérifiez que la table *livre* a été correctement mise à jour en exécutant la cellule suivante

In [140]:
SELECT * FROM livre;

id	titre	id_auteur	ann_publi	note
1	1984	1	1949	7
6	Chroniques martiennes	4	1950	5
9	Les Robots	3	1950	6
11	Ravage	6	1943	5